version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
